package tn.pi.remoteflowapplication.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import tn.pi.remoteflowapplication.domain.event.DomainEvent;
import tn.pi.remoteflowapplication.domain.event.TeleworkRequestApprovedEvent;
import tn.pi.remoteflowapplication.domain.event.TeleworkRequestRejectedEvent;
import tn.pi.remoteflowapplication.domain.event.TeleworkRequestSubmittedEvent;
import tn.pi.remoteflowapplication.domain.state.RequestStatus;

import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Entity
@Table(name = "telework_requests", indexes = {
        @Index(name = "idx_telework_employee_id", columnList = "employee_id"),
        @Index(name = "idx_telework_state", columnList = "state"),
        @Index(name = "idx_telework_created_at", columnList = "created_at"),
        @Index(name = "idx_telework_manager_external_id", columnList = "manager_external_id"),
        @Index(name = "idx_telework_hr_external_id", columnList = "hr_external_id"),
        @Index(name = "idx_telework_team_id", columnList = "team_id"),
        @Index(name = "idx_telework_process_instance_id", columnList = "process_instance_id")
})
public class TeleworkRequest extends DemandeTeletravail {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "employee_id", nullable = false, updatable = false)
    private String employeeId;

    @Column(name = "start_date", nullable = false)
    private LocalDate startDate;

    @Column(name = "end_date", nullable = false)
    private LocalDate endDate;

    @Column(name = "alfresco_node_id")
    private String alfrescoNodeId;

    @Column(name = "agreement_node_id")
    private String agreementNodeId;
    @Column(name = "archive_node_id")
    private String archiveNodeId;

    @Enumerated(EnumType.STRING)
    @Column(name = "state", nullable = false, columnDefinition = "ENUM('SUBMITTED', 'MANAGER_APPROVED', 'APPROVED', 'REJECTED', 'SPECIAL')")
    private RequestStatus status;

    @Column(name = "decision_comment")
    private String decisionComment;

    @Column(name = "justification_reason", length = 500)
    private String justificationReason;

    @Column(name = "manager_comment", length = 500)
    private String managerComment;

    @Column(name = "hr_comment", length = 500)
    private String hrComment;

    @Column(name = "process_instance_id")
    private String processInstanceId;

    @Column(name = "submitted_at", nullable = false)
    private Instant submittedAt;

    @Column(name = "manager_decision_at")
    private Instant managerDecisionAt;

    @Column(name = "hr_decision_at")
    private Instant hrDecisionAt;

    @Column(name = "approved_at")
    private Instant approvedAt;

    @Column(name = "rejected_at")
    private Instant rejectedAt;

    @Column(name = "manager_external_id")
    private String managerExternalId;

    @Column(name = "hr_external_id")
    private String hrExternalId;

    @Column(name = "team_id")
    private Long teamId;

    @Transient
    private final List<DomainEvent> domainEvents = new ArrayList<>();

    protected TeleworkRequest() {
    }

    @Override
    protected void registerAudit(String action, String entite, String utilisateur) {
        // Fix Defect 5: Delegation to subclass for audit registration.
        this.auditLogs.add(new AuditLog(action, entite, utilisateur, this));
    }

    private TeleworkRequest(String employeeId, LocalDate startDate, LocalDate endDate) {
        if (startDate != null && endDate != null && startDate.isAfter(endDate)) {
            throw new IllegalArgumentException("Start date cannot be after end date");
        }
        this.employeeId = employeeId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = RequestStatus.SUBMITTED;
        this.submittedAt = Instant.now();
        initDemandeMetadata(employeeId, startDate, endDate);
        soumettreDemande();
        // REMOVED: Immediate event registration to avoid null ID. Fixes Defect 2.
    }

    @jakarta.persistence.PostPersist
    public void onPersist() {
        // Fix Defect 2: Register event only after ID is generated by the database.
        registerEvent(new TeleworkRequestSubmittedEvent(
                this.id,
                this.employeeId,
                this.startDate,
                this.endDate));
    }

    public static TeleworkRequest create(String employeeId, LocalDate startDate, LocalDate endDate) {
        return new TeleworkRequest(employeeId, startDate, endDate);
    }

    public void linkProcess(String processInstanceId) {
        this.processInstanceId = processInstanceId;
        if (processInstanceId != null && !processInstanceId.isBlank()) {
            if (getWorkflowInstance() == null) {
                bindWorkflowInstance(new WorkflowInstance(processInstanceId, this.status.name(), this));
            } else {
                getWorkflowInstance().avancerWorkflow(this.status.name());
            }
        }
    }

    public void attachJustificatif(String nodeId) {
        if (nodeId != null && nodeId.startsWith("workspace://SpacesStore/")) {
            nodeId = nodeId.substring("workspace://SpacesStore/".length());
        }
        this.alfrescoNodeId = nodeId;
        if (nodeId != null && !nodeId.isBlank()) {
            addJustificatif(new Justificatif(
                    "justificatif-" + nodeId,
                    "ALFRESCO",
                    nodeId,
                    this));
        }
    }

    public void approveByManager(String comment) {
        if (this.status != RequestStatus.SUBMITTED && this.status != RequestStatus.SPECIAL) {
            throw new IllegalStateException("Impossible d'approuver (Manager) une demande a l'etat " + status);
        }
        this.status = RequestStatus.MANAGER_APPROVED;
        if (comment != null && !comment.trim().isEmpty()) {
            this.decisionComment = comment;
            this.managerComment = comment;
        }
        this.managerDecisionAt = Instant.now();
        if (getWorkflowInstance() != null) {
            getWorkflowInstance().avancerWorkflow(this.status.name());
        }
    }

    public void rejectByManager(String comment) {
        if (this.status != RequestStatus.SUBMITTED && this.status != RequestStatus.SPECIAL) {
            throw new IllegalStateException("Impossible de rejeter (Manager) une demande a l'etat " + status);
        }
        this.status = RequestStatus.REJECTED;
        if (comment != null && !comment.trim().isEmpty()) {
            this.decisionComment = comment;
            this.managerComment = comment;
        }
        this.managerDecisionAt = Instant.now();
        if (getWorkflowInstance() != null) {
            getWorkflowInstance().avancerWorkflow(this.status.name());
        }
        registerEvent(new TeleworkRequestRejectedEvent(
                this.id,
                this.employeeId,
                comment));
    }

    public void approveByHR(String comment) {
        if (this.status != RequestStatus.MANAGER_APPROVED) {
            throw new IllegalStateException("Impossible d'approuver (HR) une demande a l'etat " + status);
        }
        this.status = RequestStatus.APPROVED;
        if (comment != null && !comment.trim().isEmpty()) {
            this.decisionComment = comment;
            this.hrComment = comment;
        }
        this.hrDecisionAt = Instant.now();
        if (getWorkflowInstance() != null) {
            getWorkflowInstance().avancerWorkflow(this.status.name());
        }
        registerEvent(new TeleworkRequestApprovedEvent(
                this.id,
                this.employeeId,
                comment));
    }

    public void rejectByHR(String comment) {
        if (this.status != RequestStatus.MANAGER_APPROVED) {
            throw new IllegalStateException("Impossible de rejeter (HR) une demande a l'etat " + status);
        }
        this.status = RequestStatus.REJECTED;
        if (comment != null && !comment.trim().isEmpty()) {
            this.decisionComment = comment;
            this.hrComment = comment;
        }
        this.hrDecisionAt = Instant.now();
        if (getWorkflowInstance() != null) {
            getWorkflowInstance().avancerWorkflow(this.status.name());
        }
        registerEvent(new TeleworkRequestRejectedEvent(
                this.id,
                this.employeeId,
                comment));
    }

    public void markAsSpecial() {
        this.status = RequestStatus.SPECIAL;
    }

    public void recordManagerDecision(String managerId, Instant decisionAt) {
        this.managerExternalId = managerId;
        this.managerDecisionAt = decisionAt == null ? Instant.now() : decisionAt;
    }

    public void recordHrDecision(String hrId, Instant decisionAt) {
        this.hrExternalId = hrId;
        this.hrDecisionAt = decisionAt == null ? Instant.now() : decisionAt;
    }

    public void recordApprovedAt(Instant value) {
        this.approvedAt = value == null ? Instant.now() : value;
    }

    public void recordRejectedAt(Instant value) {
        this.rejectedAt = value == null ? Instant.now() : value;
    }

    public void assignTeamId(Long value) {
        this.teamId = value;
    }

    @Override
    public void annulerDemande(String utilisateur) {
        if (this.status == RequestStatus.SUBMITTED || this.status == RequestStatus.SPECIAL || this.status == RequestStatus.MANAGER_APPROVED) {
            this.status = RequestStatus.REJECTED;
        }
    }

    private void registerEvent(DomainEvent event) {
        this.domainEvents.add(event);
    }

    public List<DomainEvent> pullDomainEvents() {
        List<DomainEvent> events = new ArrayList<>(domainEvents);
        domainEvents.clear();
        return events;
    }

    public Long getId() {
        return id;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public LocalDate getDateDebut() {
        return startDate;
    }

    public LocalDate getDateFin() {
        return endDate;
    }

    public RequestStatus getStatus() {
        return status;
    }

    public RequestStatus getStatut() {
        return status;
    }

    public String getAlfrescoNodeId() {
        return alfrescoNodeId;
    }

    public String getAgreementNodeId() {
        return agreementNodeId;
    }

    public void linkAgreementNode(String agreementNodeId) {
        this.agreementNodeId = agreementNodeId;
    }

    public String getArchiveNodeId() {
        return archiveNodeId;
    }

    public void setArchiveNodeId(String archiveNodeId) {
        this.archiveNodeId = archiveNodeId;
    }

    public Optional<String> getDecisionComment() {
        return Optional.ofNullable(decisionComment);
    }

    public String getJustificationReason() {
        return justificationReason;
    }

    public void setJustificationReason(String justificationReason) {
        this.justificationReason = justificationReason;
    }

    public String getManagerComment() {
        return managerComment;
    }

    public String getHrComment() {
        return hrComment;
    }

    public String getProcessInstanceId() {
        return processInstanceId;
    }

    public Instant getSubmittedAt() {
        return submittedAt;
    }

    public Instant getManagerDecisionAt() {
        return managerDecisionAt;
    }

    public Instant getHrDecisionAt() {
        return hrDecisionAt;
    }

    public Instant getApprovedAt() {
        return approvedAt;
    }

    public Instant getRejectedAt() {
        return rejectedAt;
    }

    public String getManagerExternalId() {
        return managerExternalId;
    }

    public String getHrExternalId() {
        return hrExternalId;
    }

    public Long getTeamId() {
        return teamId;
    }
}
